swagger: "2.0"
info:
  description: "APIs to manage branch and atm locations for Bank X"
  version: "0.0.1"
  title: "Bank X - Location API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "sdavisstockholm-eval-test.apigee.net"
basePath: "/location/v1"
tags:
- name: "branch"
  description: "Manage Branches"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "atm"
  description: "Manage ATMs"
schemes:
- "https"
paths:
  /atms:
    get:
      tags:
      - "atm"
      summary: "Get ATMs"
      description: "Get All Automated Teller Machine locations. This API could be used with Google Maps to help taxi services to find ATMs on the way home for their customers."
      operationId: "getATMs"
      produces:
      - "application/json"
      responses:
        404:
          description: "No ATMs found"
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ATM"
  /atms/{atmId}:
    get:
      tags:
      - "atm"
      summary: "Get ATMs"
      description: "Get All Automated Teller Machine locations. This API could be used with Google Maps to help taxi services to find ATMs on the way home for their customers."
      operationId: "getATMById"
      produces:
      - "application/json"
      parameters:
        - in: path
          name: atmId
          type: integer
          required: true
          description: the unique identifier of the ATM
      responses:
        404:
          description: "No ATMs found"
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ATM"              
definitions:
  ATM:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      address:
        type: "integer"
        format: "int64"
      freeToUse:
        type: "boolean"
        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
